create table public.todos_list (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  user_id uuid not null,
  name character varying not null,
  description text null,
  constraint todos_list_pkey primary key (id),
  constraint todos_list_user_id_fkey foreign KEY (user_id) references auth.users (id),
  constraint todos_list_user_id_fkey1 foreign KEY (user_id) references todos_users (user_id) on delete CASCADE
) TABLESPACE pg_default;
