create table public.todos_items (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  list_id bigint not null,
  name character varying not null,
  description text null,
  url text null,
  tags character varying[] null,
  image_url text null,
  checked boolean null,
  constraint todos_items_pkey primary key (id),
  constraint todos_items_list_id_fkey foreign KEY (list_id) references todos_list (id) on delete CASCADE
) TABLESPACE pg_default;
