create table public.todos_share (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  list_id bigint not null,
  share_to uuid not null,
  share_level smallint not null default '0'::smallint,
  constraint todos_share_pkey primary key (id),
  constraint todos_share_list_id_fkey foreign KEY (list_id) references todos_list (id),
  constraint todos_share_share_to_fkey foreign KEY (share_to) references auth.users (id) on delete CASCADE
) TABLESPACE pg_default;
