create table public.todos_users (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    user_id uuid not null,
    name character varying not null,
    email text not null,
    constraint todos_users_pkey primary key (id),
    constraint todos_users_user_id_idx unique (user_id),
    constraint todos_users_user_id_fkey foreign KEY (user_id) references auth.users (id) on delete NO ACTION on update NO ACTION
) TABLESPACE pg_default;

